image: snoyberg/stackage:nightly
before_script:
# Get latest stack
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C /usr/local/bin
  - apt-get update && apt-get install -y make xz-utils libmono-2.0-dev mono-mcs fsharp libglib2.0-dev
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
build:
  cache:
    paths:
      - _cache
      - .stack-work
  script:
    - stack build
    - stack test
    - stack bench
    - stack exec clr-typed-demo
    - stack exec clr-inline-demo
