before_script:
  - apt-get update && apt-get install -y make xz-utils gcc libc6 clang libgmp-dev zlib1g-dev
  - export STACK_ROOT=`pwd`/.stack
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C /usr/bin
  - stack setup
  - stack install --only-dependencies

.test: &test
  script:
    # explicit enumeration to exclude the clr-typed test suite
    - stack build clr-typed
    - stack test clr-import-gen
    - stack test clr-inline
    - stack bench clr-inline
    - stack exec clr-typed-demo

mono4.2.1:
  image: mono:4.2.1
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test

mono4.2.2:
  image: mono:4.2.2
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test

mono4.2.3:
  image: mono:4.2.3
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test

mono4.2.4:
  image: mono:4.2.4
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test

mono4.4.0:
  image: mono:4.4.0
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test

mono4.6.0:
  image: mono:4.6.0
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test

mono4.8.0:
  image: mono:4.8.0
  cache:
    paths:
      - _cache
      - .stack-work
  <<: *test
