image: snoyberg/stackage:nightly
before_script:
# Get latest stack
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C /usr/local/bin

  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo 'deb http://download.mono-project.com/repo/debian wheezy main' | tee /etc/apt/sources.list.d/mono-xamarin.list 
  - echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list 
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list 
  - apt-get update && apt-get install -y make xz-utils libmono-2.0-dev fsharp libglib2.0-dev
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
build:
  cache:
    paths:
      - _cache
      - .stack-work
  script:
    - stack build
    - stack test
    - stack bench
    - stack exec clr-typed-demo
    - stack exec clr-inline-demo
