cache:
- "c:\\sr" # stack root, short paths == less problems

build: off

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    VSVER: 14

install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH% # for curl
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe
- stack setup > nul
- ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
- echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
- call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

test_script:
- echo "" | stack --no-terminal build --flag clr-host:enable_dotnet
- stack test clr-typed
- stack test clr-import-gen
- stack test clr-inline
- stack bench clr-inline
- stack build clr-inline-demo
# - stack exec assemblyDeps TODO copy the assembly to the stack local-install-root
